name       : qemu
version    : 4.1.0
homepage   : https://wiki.qemu.org/Main_Page
release    : 37
source     :
    - https://download.qemu.org/qemu-4.1.0.tar.xz : 656e60218689bdeec69903087fd7582d5d3e72238d02f4481d8dc6d79fd909c6
license    : GPL-2.0-only
component  : virt
summary    : QEMU is a generic and open source machine emulator and virtualizer.
description: |
    QEMU is a generic and open source machine emulator and virtualizer.

    When used as a machine emulator, QEMU can run OSes and programs made for one machine (e.g. an ARM board) on a different machine (e.g. your own PC). By using dynamic translation, it achieves very good performance.

    When used as a virtualizer, QEMU achieves near native performances by executing the guest code directly on the host CPU. QEMU supports virtualization when executing under the Xen hypervisor or using the KVM kernel module in Linux. When using KVM, QEMU can virtualize x86, server and embedded PowerPC, and S390 guests.
builddeps  :
    - pkgconfig(SDL2_image)
    - pkgconfig(alsa)
    - pkgconfig(bluez)
    - pkgconfig(epoxy)
    - pkgconfig(glu)
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcacard)
    - pkgconfig(libcap)
    - pkgconfig(libcurl)
    - pkgconfig(libdrm)
    - pkgconfig(libpng)
    - pkgconfig(libpulse)
    - pkgconfig(libsasl2)
    - pkgconfig(libseccomp)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libusbredirhost)
    - pkgconfig(spice-protocol)
    - pkgconfig(spice-server)
    - pkgconfig(virglrenderer)
    - pkgconfig(x11)
    - bzip2-devel
    - libaio-devel
    - lzo-devel
setup      : |
    ./configure --prefix=/usr \
                --libdir=%libdir% \
                --sysconfdir=/etc \
                --libexecdir=%libdir%/qemu \
                --localstatedir=/var \
                --audio-drv-list=pa,alsa \
                --disable-strip \
                --enable-attr \
                --enable-bluez \
                --enable-curl \
                --enable-curses \
                --enable-gtk \
                --enable-kvm \
                --enable-libusb \
                --enable-linux-aio \
                --enable-opengl \
                --enable-pie \
                --enable-sdl-image \
                --enable-spice \
                --enable-vhost-net \
                --enable-virglrenderer \
                --enable-virtfs \
                --enable-vnc \
                --enable-vnc-jpeg \
                --enable-vnc-png \
                --target-list='aarch64-softmmu arm-linux-user arm-softmmu i386-linux-user i386-softmmu mips-linux-user mips-softmmu mipsel-linux-user mipsel-softmmu x86_64-linux-user x86_64-softmmu'
build      : |
    %make
install    : |
    %make_install
    # Qemu installs this during build..
    rm -rf $installdir/var
check      : |
    # Fails on char/websocket because of "too few tests run"
    %make check V=1 || :
